env:
  name: "Pendulum"
  m: 0.055
  g: 9.81
  l: 0.042
  J: 1.91e-4
  b: 3.0e-6
  K: 0.0536
  R: 9.5
  max_voltage: 3
  max_speed: 47.12388980384689  # 15pi
  Ts: 0.005
  max_steps: 500
  initial_act_interval: 20
  act_interval_decay: 0.98
  final_act_interval: 1

agent:
  name: "DQN"
  gamma: 0.98
  epsilon: 0.9
  epsilon_decay: 0.9
  epsilon_decay_steps: 1
  epsilon_min: 0.0001
  learning_rate: 0.001
  learning_rate_decay: 0.95
  learning_rate_decay_steps: 10
  learning_rate_min: 5.0e-6
  input_dim: 2  # pendulum state: [alpha, dot_alpha]
  output_dim: 3
  hidden_dims: [128, 128]
  target_update_interval: 20
  device: "cuda"
  actions: [-3, 0, 3]  # voltage actions
  input_encoding: false
  input_encoding_dim: 0

training:
  mode: "off-policy"  # "off-policy" or "on-policy"
  seed: 1
  num_episodes: 200
  batch_size: 4096
  min_buffer_size: 10240
  buffer_size: 102400
  train_interval_steps: 10
  save_interval: 50
  log_interval: 1
  checkpoint_path: "./checkpoints"
  log_path: "./logs"