env:
  name: "Curling"
  r: 1.0 
  m: 1.0 
  h: 100.0  
  w: 100.0  
  rebound_coefficient: 0.9 
  initial_speed_range: [-10, 10] 
  dt: 0.01  
  max_steps: 3000
  num_steps_per_step: 10
  initial_act_interval: 1
  act_interval_decay: 1
  final_act_interval: 1
  normalize: false

agent:
  name: "DQN"
  gamma: 1
  epsilon: 0.9
  epsilon_decay: 0.975
  epsilon_decay_steps: 1
  epsilon_min: 0.01
  learning_rate: 0.001
  learning_rate_decay: 0.95
  learning_rate_decay_steps: 10
  learning_rate_min: 5.0e-6
  input_dim: 6  # [pos_x, pos_y, vel_x, vel_y, target_x, target_y] 
  output_dim: 4
  actions: [[5, 0], [0, 5], [-5, 0], [0, -5]]  # [up, right, down, left]
  hidden_dims: [128, 128]
  target_update_interval: 500
  device: "cuda"
  input_encoding: false
  input_encoding_dim: 0

training:
  mode: "off-policy"  # "off-policy" or "on-policy"
  seed: 1
  num_episodes: 200
  batch_size: 4096
  min_buffer_size: 10240
  buffer_size: 102400
  train_interval_steps: 1
  save_interval: 50
  log_interval: 1
  checkpoint_path: "./checkpoints/curling"
  log_path: "./logs/curling"
